export const ADD_MOVIE_TO_WATCHLIST='ADD_MOVIE_TO_WATCHLIST';
export const REMOUVE_MOVIE_FROM_WATCHLIST='REMOUVE_MOVIE_FROM_WATCHLIST';
export const ADD_MOVIE_TO_WATCHED='ADD_MOVIE_TO_WATCHED';
export const REMOUVE_MOVIE_FROM_WATCHED='REMOUVE_MOVIE_FROM_WATCHED';
export const MOVE_TO_WATCHLIST='MOVE_TO_WATCHLIST';
